---

- hosts: all
  roles:
    - { role: /home/osboxes/ansible/ansible-role-patching/roles/prereq }
    - { role: /home/osboxes/ansible/ansible-role-patching/roles/preinstall }
    - { role: /home/osboxes/ansible/ansible-role-patching/roles/installation }
    - { role: /home/osboxes/ansible/ansible-role-patching/roles/postinstall }
