---

- name: Install PSU
  shell: opatch apply -force -silent {{patch_home}}{{ansible_date_time.date}}/{{patch_number}}
  register: applyPatch
  tags: Apply

- debug: var=applyPatch
  tags: Apply
