---

- name: Create patch directory
  file:
    path: "{{patch_home}}{{ansible_date_time.date}}"
    state: directory
    owner: "{{ oracle_user }}"
    group: "{{ oracle_user }}"
  tags: prereq


- name: Copy psu file
  copy:
    src: "{{folder_patch}}{{patch_filename}}"
    dest: "{{patch_home}}{{ansible_date_time.date}}"
    owner: "{{ oracle_user }}"
    mode: 0755
  tags: prereq

- name: Extract PSU zip file
  unarchive:
    src: "{{patch_home}}{{ansible_date_time.date}}/{{patch_filename}}"
    dest: "{{patch_home}}{{ansible_date_time.date}}"
    remote_src: yes
  tags: Extract
